# Generated by Django 5.0.1 on 2024-02-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_image_productsgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created', 'name')},
        ),
        migrations.AlterField(
            model_name='productsgallery',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/products/'),
        ),
    ]
